# API Settings
github_api: <github_api>
sendgrid_api: <sendgrid_api>

# Notification Settings
email_from: fromemail@domain.com
email_subject: Repo with secrets has been detected
email_template: templates/alert.html
email_notify:
    - user1@domain.com
    - user2@domain.com

# Audit Settings
targets: config/target-list.csv
whitelist: config/whitelist-patterns.txt
blacklist: config/bad-patterns.txt
log_dir: log/
